name: Retrain Model

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  train-build-push:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - run: |
          pip install mlflow
          pip install pandas
          pip install scikit-learn
          pip install matplotlib
          pip install seaborn
          pip install dagshub

      - run: |
          cd MLProject
          mlflow run .
